services:
  laravel:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: bssshop-laravel
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - bssshop

  mysql:
    image: mysql:8.0
    container_name: bssshop-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: bssshop_laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bssshop

networks:
  bssshop:

volumes:
  mysql_data: