-- Generated by d-migrate 1.7.1
-- Source: neutral schema v0.0.0-reverse "__dmigrate_reverse__:mysql:database=bssshop_laravel"
-- Target: postgresql | Generated: 2026-09-28T08:04:49.280137773Z

CREATE TABLE "blog" (
    "id" SERIAL,
    "title" VARCHAR(255) NOT NULL,
    "slug" VARCHAR(255) NOT NULL,
    "category" VARCHAR(100) NOT NULL,
    "content" TEXT NOT NULL,
    "excerpt" VARCHAR(500) NOT NULL,
    "image" VARCHAR(255),
    "author" VARCHAR(100) NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'draft' CHECK ("status" IN ('draft', 'published', 'archived')),
    "views" INTEGER NOT NULL DEFAULT 0,
    "published_at" TIMESTAMP,
    "meta_title" VARCHAR(255),
    "meta_description" VARCHAR(500),
    "meta_keywords" VARCHAR(255),
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    CONSTRAINT "blog_slug" UNIQUE ("slug"),
    PRIMARY KEY ("id")
);

CREATE TABLE "cache" (
    "key" VARCHAR(255),
    "value" TEXT NOT NULL,
    "expiration" INTEGER NOT NULL,
    PRIMARY KEY ("key")
);

CREATE TABLE "cache_locks" (
    "key" VARCHAR(255),
    "owner" VARCHAR(255) NOT NULL,
    "expiration" INTEGER NOT NULL,
    PRIMARY KEY ("key")
);

CREATE TABLE "categories" (
    "id" SERIAL,
    "parent_id" INTEGER,
    "name" VARCHAR(100) NOT NULL,
    "slug" VARCHAR(100) NOT NULL,
    "icon" VARCHAR(50),
    "description" TEXT,
    "status" BOOLEAN NOT NULL DEFAULT TRUE,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    CONSTRAINT "categories_slug" UNIQUE ("slug"),
    PRIMARY KEY ("id")
);

CREATE TABLE "ci4_cache" (
    "key" VARCHAR(255),
    "value" TEXT NOT NULL,
    "expiration" INTEGER NOT NULL,
    PRIMARY KEY ("key")
);

CREATE TABLE "ci4_cache_locks" (
    "key" VARCHAR(255),
    "owner" VARCHAR(255) NOT NULL,
    "expiration" INTEGER NOT NULL,
    PRIMARY KEY ("key")
);

CREATE TABLE "ci4_failed_jobs" (
    "id" BIGSERIAL,
    "uuid" VARCHAR(255) NOT NULL,
    "connection" TEXT NOT NULL,
    "queue" TEXT NOT NULL,
    "payload" TEXT NOT NULL,
    "exception" TEXT NOT NULL,
    "failed_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ci4_failed_jobs_failed_jobs_uuid_unique" UNIQUE ("uuid"),
    PRIMARY KEY ("id")
);

CREATE TABLE "ci4_job_batches" (
    "id" VARCHAR(255),
    "name" VARCHAR(255) NOT NULL,
    "total_jobs" INTEGER NOT NULL,
    "pending_jobs" INTEGER NOT NULL,
    "failed_jobs" INTEGER NOT NULL,
    "failed_job_ids" TEXT NOT NULL,
    "options" TEXT,
    "cancelled_at" INTEGER,
    "created_at" INTEGER NOT NULL,
    "finished_at" INTEGER,
    PRIMARY KEY ("id")
);

CREATE TABLE "ci4_jobs" (
    "id" BIGSERIAL,
    "queue" VARCHAR(255) NOT NULL,
    "payload" TEXT NOT NULL,
    "attempts" SMALLINT NOT NULL,
    "reserved_at" INTEGER,
    "available_at" INTEGER NOT NULL,
    "created_at" INTEGER NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "ci4_migrations" (
    "id" BIGSERIAL,
    "version" VARCHAR(255) NOT NULL,
    "class" VARCHAR(255) NOT NULL,
    "group" VARCHAR(255) NOT NULL,
    "namespace" VARCHAR(255) NOT NULL,
    "time" INTEGER NOT NULL,
    "batch" INTEGER NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "contact_messages" (
    "id" SERIAL,
    "name" VARCHAR(100) NOT NULL,
    "email" VARCHAR(100) NOT NULL,
    "subject" VARCHAR(255),
    "message" TEXT NOT NULL,
    "status" TEXT DEFAULT 'unread' CHECK ("status" IN ('unread', 'read', 'replied')),
    "admin_reply" TEXT,
    "replied_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "created_at" TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "failed_jobs" (
    "id" BIGSERIAL,
    "uuid" VARCHAR(255) NOT NULL,
    "connection" TEXT NOT NULL,
    "queue" TEXT NOT NULL,
    "payload" TEXT NOT NULL,
    "exception" TEXT NOT NULL,
    "failed_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "failed_jobs_failed_jobs_uuid_unique" UNIQUE ("uuid"),
    PRIMARY KEY ("id")
);

CREATE TABLE "faqs" (
    "id" SERIAL,
    "question" VARCHAR(255) NOT NULL,
    "answer" TEXT NOT NULL,
    "category" VARCHAR(100),
    "status" TEXT DEFAULT 'active' CHECK ("status" IN ('active', 'inactive')),
    "order" INTEGER DEFAULT 0,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "feature_category_mapping" (
    "id" SERIAL,
    "feature_id" INTEGER NOT NULL,
    "category_id" INTEGER,
    "sub_category_id" INTEGER,
    "created_at" TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "features" (
    "id" SERIAL,
    "name" VARCHAR(150) NOT NULL,
    "input_type" TEXT NOT NULL DEFAULT 'text' CHECK ("input_type" IN ('text', 'dropdown', 'checkbox')),
    "options" TEXT,
    "status" BOOLEAN NOT NULL DEFAULT TRUE,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "home_banner" (
    "id" SERIAL,
    "badge_text" VARCHAR(100),
    "title_line1" VARCHAR(200),
    "title_line2" VARCHAR(200),
    "subtitle" VARCHAR(500),
    "button_text" VARCHAR(100),
    "button_link" VARCHAR(255),
    "button_icon" VARCHAR(50),
    "is_active" BOOLEAN DEFAULT TRUE,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "job_batches" (
    "id" VARCHAR(255),
    "name" VARCHAR(255) NOT NULL,
    "total_jobs" INTEGER NOT NULL,
    "pending_jobs" INTEGER NOT NULL,
    "failed_jobs" INTEGER NOT NULL,
    "failed_job_ids" TEXT NOT NULL,
    "options" TEXT,
    "cancelled_at" INTEGER,
    "created_at" INTEGER NOT NULL,
    "finished_at" INTEGER,
    PRIMARY KEY ("id")
);

CREATE TABLE "jobs" (
    "id" BIGSERIAL,
    "queue" VARCHAR(255) NOT NULL,
    "payload" TEXT NOT NULL,
    "attempts" SMALLINT NOT NULL,
    "reserved_at" INTEGER,
    "available_at" INTEGER NOT NULL,
    "created_at" INTEGER NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "languages" (
    "id" SERIAL,
    "code" VARCHAR(10) NOT NULL,
    "name" VARCHAR(50) NOT NULL,
    "native_name" VARCHAR(50) NOT NULL,
    "flag" VARCHAR(10),
    "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
    "is_default" BOOLEAN NOT NULL DEFAULT FALSE,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    CONSTRAINT "languages_code" UNIQUE ("code"),
    PRIMARY KEY ("id")
);

CREATE TABLE "migrations" (
    "id" SERIAL,
    "migration" VARCHAR(255) NOT NULL,
    "batch" INTEGER NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "navigation_menus" (
    "id" SERIAL,
    "menu_name" VARCHAR(100) NOT NULL,
    "url" VARCHAR(255) NOT NULL,
    "display_header" BOOLEAN NOT NULL DEFAULT FALSE,
    "display_footer" BOOLEAN NOT NULL DEFAULT FALSE,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "status" BOOLEAN NOT NULL DEFAULT TRUE,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "personal_access_tokens" (
    "id" BIGSERIAL,
    "tokenable_type" VARCHAR(255) NOT NULL,
    "tokenable_id" BIGINT NOT NULL,
    "name" TEXT NOT NULL,
    "token" VARCHAR(64) NOT NULL,
    "abilities" TEXT,
    "last_used_at" TIMESTAMP,
    "expires_at" TIMESTAMP,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    CONSTRAINT "personal_access_tokens_personal_access_tokens_token_unique" UNIQUE ("token"),
    PRIMARY KEY ("id")
);

CREATE TABLE "product_categories" (
    "id" SERIAL,
    "parent_id" INTEGER,
    "name" VARCHAR(100) NOT NULL,
    "icon" VARCHAR(50) DEFAULT 'bi-box',
    "item_count" INTEGER DEFAULT 0,
    "link" VARCHAR(255) DEFAULT '#',
    "sort_order" INTEGER DEFAULT 0,
    "is_active" BOOLEAN DEFAULT TRUE,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "settings" (
    "id" SERIAL,
    "key" VARCHAR(100) NOT NULL,
    "value" TEXT NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    CONSTRAINT "settings_key" UNIQUE ("key"),
    PRIMARY KEY ("id")
);

CREATE TABLE "themes" (
    "id" SERIAL,
    "name" VARCHAR(50) NOT NULL,
    "display_name" VARCHAR(100) NOT NULL,
    "description" TEXT,
    "preview_image" VARCHAR(255),
    "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
    "is_default" BOOLEAN NOT NULL DEFAULT FALSE,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    CONSTRAINT "themes_name" UNIQUE ("name"),
    PRIMARY KEY ("id")
);

CREATE TABLE "timezones" (
    "id" SERIAL,
    "name" VARCHAR(100) NOT NULL,
    "offset" VARCHAR(10) NOT NULL,
    "abbreviation" VARCHAR(10) NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
    "is_default" BOOLEAN NOT NULL DEFAULT FALSE,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    CONSTRAINT "timezones_name" UNIQUE ("name"),
    PRIMARY KEY ("id")
);

CREATE TABLE "user_preferences" (
    "id" BIGSERIAL,
    "user_id" BIGINT NOT NULL,
    "language" VARCHAR(10) NOT NULL DEFAULT 'en',
    "timezone" VARCHAR(50) NOT NULL DEFAULT 'UTC',
    "theme" VARCHAR(50) NOT NULL DEFAULT 'light',
    "notifications" VARCHAR(10) NOT NULL DEFAULT 'on',
    "newsletter" BOOLEAN NOT NULL DEFAULT FALSE,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "users" (
    "id" SERIAL,
    "name" VARCHAR(100) NOT NULL,
    "email" VARCHAR(100) NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'user' CHECK ("role" IN ('admin', 'user')),
    "status" TEXT NOT NULL DEFAULT 'active' CHECK ("status" IN ('active', 'inactive')),
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "phone" VARCHAR(20),
    "avatar" VARCHAR(255),
    "address" VARCHAR(255),
    "city" VARCHAR(100),
    "state" VARCHAR(100),
    "postal_code" VARCHAR(20),
    "country" VARCHAR(50) DEFAULT 'US',
    "notes" TEXT,
    "super_admin" BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT "users_email" UNIQUE ("email"),
    PRIMARY KEY ("id")
);

CREATE TABLE "feature_values" (
    "id" SERIAL,
    "feature_id" INTEGER NOT NULL,
    "value" VARCHAR(255) NOT NULL,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "status" BOOLEAN NOT NULL DEFAULT TRUE,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "products" (
    "id" SERIAL,
    "name" VARCHAR(200) NOT NULL,
    "slug" VARCHAR(200) NOT NULL,
    "description" TEXT NOT NULL,
    "price" DECIMAL(10,2) NOT NULL,
    "image" VARCHAR(255),
    "stock" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'active' CHECK ("status" IN ('active', 'inactive')),
    "category_id" INTEGER,
    "subcategory_id" INTEGER,
    "rating" DECIMAL(2,1) DEFAULT 0.0,
    "discount" INTEGER DEFAULT 0,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "short_description" VARCHAR(500),
    "sale_price" DECIMAL(10,2),
    "sku" VARCHAR(100),
    "tags" VARCHAR(255),
    "weight" DECIMAL(10,2),
    "length" DECIMAL(10,2),
    "width" DECIMAL(10,2),
    "height" DECIMAL(10,2),
    "is_featured" BOOLEAN DEFAULT FALSE,
    "is_home" BOOLEAN DEFAULT FALSE,
    CONSTRAINT "products_slug" UNIQUE ("slug"),
    CONSTRAINT "products_sku" UNIQUE ("sku"),
    PRIMARY KEY ("id")
);

CREATE TABLE "orders" (
    "id" SERIAL,
    "user_id" INTEGER NOT NULL,
    "order_number" VARCHAR(50) NOT NULL,
    "razorpay_order_id" VARCHAR(255),
    "razorpay_payment_id" VARCHAR(255),
    "razorpay_signature" VARCHAR(255),
    "payment_method_display" VARCHAR(50),
    "total" DECIMAL(10,2) NOT NULL,
    "payment_status" TEXT NOT NULL DEFAULT 'pending' CHECK ("payment_status" IN ('pending', 'paid', 'failed', 'refunded', 'partially_refunded')),
    "order_status" TEXT NOT NULL DEFAULT 'pending' CHECK ("order_status" IN ('pending', 'processing', 'completed', 'cancelled')),
    "shipping_address" TEXT NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    CONSTRAINT "orders_order_number" UNIQUE ("order_number"),
    PRIMARY KEY ("id")
);

CREATE TABLE "product_feature_values" (
    "id" SERIAL,
    "product_id" INTEGER NOT NULL,
    "feature_id" INTEGER NOT NULL,
    "value" VARCHAR(255),
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "product_images" (
    "id" SERIAL,
    "product_id" INTEGER NOT NULL,
    "image" VARCHAR(255) NOT NULL,
    "is_primary" BOOLEAN DEFAULT FALSE,
    "sort_order" INTEGER DEFAULT 0,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "product_specifications" (
    "id" SERIAL,
    "product_id" INTEGER NOT NULL,
    "label" VARCHAR(255) NOT NULL,
    "value" TEXT NOT NULL,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "product_variants" (
    "id" SERIAL,
    "product_id" INTEGER NOT NULL,
    "sku" VARCHAR(100) NOT NULL,
    "slug" VARCHAR(255) NOT NULL,
    "price" DECIMAL(10,2) NOT NULL DEFAULT 0.0,
    "sale_price" DECIMAL(10,2),
    "discount" DECIMAL(5,2) DEFAULT 0.0,
    "rating" DECIMAL(2,1) DEFAULT 0.0,
    "stock" INTEGER NOT NULL DEFAULT 0,
    "status" BOOLEAN NOT NULL DEFAULT TRUE,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "wishlist" (
    "id" SERIAL,
    "user_id" INTEGER NOT NULL,
    "product_id" INTEGER NOT NULL,
    "variant_id" INTEGER NOT NULL,
    "created_at" TIMESTAMP,
    CONSTRAINT "wishlist_user_id_product_id" UNIQUE ("user_id", "product_id"),
    PRIMARY KEY ("id")
);

CREATE TABLE "invoices" (
    "id" SERIAL,
    "order_id" INTEGER NOT NULL,
    "invoice_number" VARCHAR(50) NOT NULL,
    "user_id" INTEGER NOT NULL,
    "issue_date" DATE NOT NULL,
    "due_date" DATE NOT NULL,
    "subtotal" DECIMAL(10,2) NOT NULL DEFAULT 0.0,
    "tax" DECIMAL(10,2) NOT NULL DEFAULT 0.0,
    "discount" DECIMAL(10,2) NOT NULL DEFAULT 0.0,
    "total" DECIMAL(10,2) NOT NULL DEFAULT 0.0,
    "status" TEXT NOT NULL DEFAULT 'unpaid' CHECK ("status" IN ('paid', 'unpaid', 'overdue', 'cancelled')),
    "notes" TEXT,
    "payment_method" VARCHAR(50),
    "payment_date" TIMESTAMP,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    CONSTRAINT "invoices_invoice_number" UNIQUE ("invoice_number"),
    PRIMARY KEY ("id")
);

CREATE TABLE "order_items" (
    "id" SERIAL,
    "order_id" INTEGER NOT NULL,
    "product_id" INTEGER NOT NULL,
    "variant_id" INTEGER DEFAULT 0,
    "quantity" INTEGER NOT NULL,
    "price" DECIMAL(10,2) NOT NULL,
    "subtotal" DECIMAL(10,2) NOT NULL DEFAULT 0.0,
    "shipping" DECIMAL(10,2) DEFAULT 0.0,
    "tax" DECIMAL(10,2) DEFAULT 0.0,
    "created_at" TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "product_variant_images" (
    "id" SERIAL,
    "variant_id" INTEGER NOT NULL,
    "product_id" INTEGER NOT NULL,
    "image" VARCHAR(255) NOT NULL,
    "is_primary" BOOLEAN NOT NULL DEFAULT FALSE,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE "product_variant_values" (
    "id" SERIAL,
    "variant_id" INTEGER NOT NULL,
    "feature_id" INTEGER NOT NULL,
    "value" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE INDEX "cache_cache_expiration_index" ON "cache" ("expiration");

CREATE INDEX "cache_locks_cache_locks_expiration_index" ON "cache_locks" ("expiration");

CREATE INDEX "categories_parent_id" ON "categories" ("parent_id");

CREATE INDEX "categories_status" ON "categories" ("status");

-- [W127] Index 'cache_expiration_index' on table 'ci4_cache' was renamed to 'cache_expiration_index_2' to keep index names unique within the PostgreSQL schema (MySQL allows the same index name on several tables; PostgreSQL index names are schema-global).
-- Hint: Rename the source index if a specific PostgreSQL name is required.
CREATE INDEX "ci4_cache_cache_expiration_index_2" ON "ci4_cache" ("expiration");

-- [W127] Index 'cache_locks_expiration_index' on table 'ci4_cache_locks' was renamed to 'cache_locks_expiration_index_2' to keep index names unique within the PostgreSQL schema (MySQL allows the same index name on several tables; PostgreSQL index names are schema-global).
-- Hint: Rename the source index if a specific PostgreSQL name is required.
CREATE INDEX "ci4_cache_locks_cache_locks_expiration_index_2" ON "ci4_cache_locks" ("expiration");

CREATE INDEX "ci4_jobs_jobs_queue_index" ON "ci4_jobs" ("queue");

CREATE INDEX "feature_category_mapping_idx_category_id" ON "feature_category_mapping" ("category_id");

CREATE INDEX "feature_category_mapping_idx_feature_id" ON "feature_category_mapping" ("feature_id");

CREATE INDEX "feature_category_mapping_idx_sub_category_id" ON "feature_category_mapping" ("sub_category_id");

-- [W127] Index 'jobs_queue_index' on table 'jobs' was renamed to 'jobs_queue_index_2' to keep index names unique within the PostgreSQL schema (MySQL allows the same index name on several tables; PostgreSQL index names are schema-global).
-- Hint: Rename the source index if a specific PostgreSQL name is required.
CREATE INDEX "jobs_jobs_queue_index_2" ON "jobs" ("queue");

CREATE INDEX "navigation_menus_display_footer" ON "navigation_menus" ("display_footer");

CREATE INDEX "navigation_menus_display_header" ON "navigation_menus" ("display_header");

CREATE INDEX "navigation_menus_sort_order" ON "navigation_menus" ("sort_order");

-- [W127] Index 'status' on table 'navigation_menus' was renamed to 'status_2' to keep index names unique within the PostgreSQL schema (MySQL allows the same index name on several tables; PostgreSQL index names are schema-global).
-- Hint: Rename the source index if a specific PostgreSQL name is required.
CREATE INDEX "navigation_menus_status_2" ON "navigation_menus" ("status");

CREATE INDEX "personal_access_tokens_personal_access_tokens_expires_at_index" ON "personal_access_tokens" ("expires_at");

CREATE INDEX "personal_access_tokens_personal_access_tokens_tokenable_type_tokenable_id_index" ON "personal_access_tokens" ("tokenable_type", "tokenable_id");

CREATE INDEX "product_categories_idx_parent_id" ON "product_categories" ("parent_id");

CREATE INDEX "products_idx_products_subcategory_id" ON "products" ("subcategory_id");

CREATE INDEX "products_subcategory_id" ON "products" ("subcategory_id");

CREATE INDEX "orders_idx_razorpay_order_id" ON "orders" ("razorpay_order_id");

CREATE INDEX "orders_idx_razorpay_payment_id" ON "orders" ("razorpay_payment_id");

CREATE INDEX "product_feature_values_idx_product_feature" ON "product_feature_values" ("product_id", "feature_id");

CREATE INDEX "product_images_product_id" ON "product_images" ("product_id");

-- [W127] Index 'product_id' on table 'product_specifications' was renamed to 'product_id_2' to keep index names unique within the PostgreSQL schema (MySQL allows the same index name on several tables; PostgreSQL index names are schema-global).
-- Hint: Rename the source index if a specific PostgreSQL name is required.
CREATE INDEX "product_specifications_product_id_2" ON "product_specifications" ("product_id");

CREATE INDEX "order_items_idx_variant_id" ON "order_items" ("variant_id");

ALTER TABLE "categories" ADD CONSTRAINT "categories_parent_id_foreign" FOREIGN KEY ("parent_id") REFERENCES "categories" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "categories" ADD CONSTRAINT "fk_categories_parent" FOREIGN KEY ("parent_id") REFERENCES "categories" ("id") ON DELETE CASCADE;

ALTER TABLE "feature_values" ADD CONSTRAINT "feature_values_feature_id_foreign" FOREIGN KEY ("feature_id") REFERENCES "features" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "products" ADD CONSTRAINT "fk_products_category" FOREIGN KEY ("category_id") REFERENCES "product_categories" ("id") ON DELETE SET NULL;

ALTER TABLE "products" ADD CONSTRAINT "fk_products_subcategory" FOREIGN KEY ("subcategory_id") REFERENCES "product_categories" ("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "orders" ADD CONSTRAINT "orders_user_id_foreign" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "product_feature_values" ADD CONSTRAINT "product_feature_values_feature_id_foreign" FOREIGN KEY ("feature_id") REFERENCES "features" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "product_feature_values" ADD CONSTRAINT "product_feature_values_product_id_foreign" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "product_images" ADD CONSTRAINT "fk_product_images_product" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE;

ALTER TABLE "product_specifications" ADD CONSTRAINT "product_specifications_product_id_foreign" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "product_variants" ADD CONSTRAINT "product_variants_product_id_foreign" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "wishlist" ADD CONSTRAINT "wishlist_product_id_foreign" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "wishlist" ADD CONSTRAINT "wishlist_user_id_foreign" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "invoices" ADD CONSTRAINT "invoices_order_id_foreign" FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "invoices" ADD CONSTRAINT "invoices_user_id_foreign" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "order_items" ADD CONSTRAINT "order_items_order_id_foreign" FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "order_items" ADD CONSTRAINT "order_items_product_id_foreign" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "product_variant_images" ADD CONSTRAINT "product_variant_images_product_id_foreign" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "product_variant_images" ADD CONSTRAINT "product_variant_images_variant_id_foreign" FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "product_variant_values" ADD CONSTRAINT "product_variant_values_feature_id_foreign" FOREIGN KEY ("feature_id") REFERENCES "features" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "product_variant_values" ADD CONSTRAINT "product_variant_values_variant_id_foreign" FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
